### PR TITLE
Adds Android namespace

### PR DESCRIPTION
**Pull request by asaarnak**
Adds a namespace attribute to the Android build.gradle, for compatibility with Android Gradle Plugin 8.0.
See:
https://github.com/flutter/packages/commit/6284c2d4e46a5d289e77cb03a9457543b97f750b

### CODE REVIEW

**Comment by asaarnak** [comment]
@JlUgia Hei. Should be good to merge. Waiting for review.

**Comment by JlUgia** [comment]
Thank you for your contribution @asaarnak.
This looks good.
PRs don't need to propose a new release or version bump. Releases are planned in separate cycles from PR.
Please remove that part to continue ahead.

**Comment by asaarnak** [comment]
@JlUgia reverted version and changelog the changelog

**Comment by JlUgia** [comment]
Thank you!

**Pull request merged**
