### PR TITLE
supporting flutter 3

### PR DESCRIPTION
**Pull request by bilalsammour**
Tested on Flutter 3

### CODE REVIEW

**Comment by bilalsammour** [comment]
Done

**Comment by Akash9151** [comment]
Any update on this, when we can get the flutter 3 version upgrade..?

**Comment by JlUgia** [comment]
Thank you for the contribution @bilalsammour. This effort seems to have the same purpose as https://github.com/google-pay/flutter-plugin/pull/129, which is being reviewed ATM.
I'm closing this PR.
Feel free to reopen and reply if the assumption is not accurate.

**Comment by JlUgia** [comment]
pay: 1.0.9 and pay_android: 1.0.7 are now published.
Thank you for your contributions.

**Pull request closed without merging**
