### PR TITLE
ios 14 fix enum errors on build xcode 12.5.1

### PR DESCRIPTION
**Pull request by vmatiukh**
xCode return build error when not checking ios versions and it break down CI system

### CODE REVIEW

**Comment by vmatiukh** [comment]
@googlebot I signed it!

**Comment by vmatiukh** [comment]
@googlebot I signed it!

**Comment by vmatiukh** [comment]
@googlebot I fixed it.

**Comment by vmatiukh** [comment]
@googlebot I fixed it.

**Comment by JlUgia** [comment]
Hi @vmatiukh, I don't seem to be able to reproduce this issue. Can you help me do so?
Also, some versions requirement in the PR do not match to the docs (eg.: checkout requires >=12).
Which target version are you using in your application?

**Comment by vmatiukh** [comment]
Hi, @JlUgia I using target version iOS 11.2

**Comment by JlUgia** [comment]
Closing in favor of #91

**Pull request closed without merging**
